version: "3.8"

services:
  db:
    image: postgres:15
    container_name: xpress_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: xpressure
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5435:5432"

  backend:
    build: ./backend
    container_name: xpress_backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: xpressure
      DB_USER: admin
      DB_PASS: password
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    # environment:
    #  - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    container_name: xpress_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  pgdata: